version: '3.8'
services:
  app:
    container_name: microservice_back
    build:
      context: ./AggregateAndMicroService
      dockerfile: Dockerfile
    ports:
      - "5271:8080"
    volumes:
      - ./AggregateAndMicroService/config.json.docker:/app/config.json
    restart: on-failure:5
    depends_on:
      - database

  database:
    container_name: microservice_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: materials
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  kafka_consumer:
    container_name: kafka_consumer
    build:
      context: ./KafkaConsumer
      dockerfile: Dockerfile
    restart: on-failure:5
    depends_on:
      - database
      - app
volumes:
  db_data:
