version: '3.8'
services:
  app:
    container_name: microservice_back
    build:
      context: ./AggregateAndMicroService
      dockerfile: Dockerfile
    ports:
      - "5271:8080"
    restart: on-failure:5
    depends_on:
      - database

  database:
    container_name: microservice_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: materials
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
